# lint.select = [
#     "E",   # flake8: Python 语法相关（如 E305）
#     "F",   # pyflakes
#     "I",   # isort
#     "UP",  # pyupgrade
# ]

lint.ignore = [
    "E501",  # 不检查行长度（让 format 处理）
    "F841",  # 局部变量未使用（有时合理）,
    "E402",
]

# 目标 Python 版本
target-version = "py313"

# 排除文件
exclude = [
    "logs",
    "static",
]